name: Testes com Robot Framework e SeleniumLibrary

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c贸digo
        uses: actions/checkout@v2

      - name: Criar diret贸rio de relat贸rios
        run: mkdir -p reports

      - name: Executar testes com Robot Framework
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/opt/robotframework/tests \
            -v ${{ github.workspace }}/reports:/opt/robotframework/reports \
            ppodgorsek/robot-framework \
            robot --variable BROWSER:chrome \
                  --variable BROWSER_OPTIONS:--no-sandbox,--disable-dev-shm-usage,--headless,--disable-gpu \
                  tests/robot_tests

      - name: Upload dos relat贸rios
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-reports
          path: reports
