name: Testes com Robot Framework e SeleniumLibrary

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Criar pasta de relatórios com permissões certas
      run: |
        mkdir -p reports
        sudo chmod -R 777 reports

    - name: Executar testes com Robot Framework (imagem estável via GHCR)
      env:
        ROBOT_OPTIONS: --variable BROWSER:chrome --variable BROWSER_OPTIONS:--no-sandbox\ --disable-dev-shm-usage\ --headless\ --disable-gpu
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/opt/robotframework/tests \
          -v ${{ github.workspace }}/reports:/opt/robotframework/reports \
          ghcr.io/ppodgorsek/robot-framework:latest

    - name: Upload dos relatórios
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-reports
        path: reports
